pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t uipath-builder .
                    docker run -v /project:/project -v output:/output uipath-builder
                    '''
                }
            }
        }
    }

}